---
title: "Jason Allen"
---

6548 Cordoba rd  
Isla Vista, CA 93117  
Email: [jcallen@ucsb.edu](mailto:jcallen@ucsb.edu?subject=[GitHub Website])  
Cell:  [707-486-4820](tel:7074864820)  
[PDF Download](./CV/Resume July 2021.pdf)
  
## Research Interests  

* Geospatial Data Analysis, Physics, Space Mission Design, Technical Visualization  
  
  
## Education  
#### University of California Santa Barbara — In Progress Physics BS  
**August 2018 - April 2019**  
  
#### Santa Rosa Junior College — Physics AA Coursework  
**August 2013 - May 2018**  

* Relevant Coursework - Classical Mechanics, Modern Physics, Calculus, Differential Equations, Linear Algebra, Programming C++, Psychology, Cultural Anthropology, Critical Thinking and Advanced Composition.  
  
  
## Research  
#### NASA Big Idea’s Challenge 2020

* I helped design a solar powered laser device to reduce dust on the lunar surface and rendered a 3D movie demonstrating our device with Blender. 

#### Team Fusion Research Review  

* Led a team of three students in creating a poster to explain hydrogen fusion to the general public. Met all deadlines and specifications without fail.    

#### Satellite Communication Antenna   

* We used a simple antenna and radio setup to receive signal from a cube satellite with free linux based software.  
  
  
## Experience
#### Knighted Ventures, Petaluma— Gaming Associate  
**December 2019 -  January 2020**  

* I assisted casino dealers full time with banking games and I was responsible for ensuring asset protection and maintaining the integrity of the games by catching mistakes at the table.  
  
#### Bouverie Preserve, Glen Ellen— Juniper (Volunteer)  
**2007 - 2013**  

* Helped lead hikes for the general public and assisted with wildlife research. 
    
      
## Languages  

* English, Japanese  
  
  
## Skills  

* Upper Division College Math  
* Computer Programming  
* Design Software  
* Team Building  
* Social Intuition  
* Project Building  
  

